### ISSUE TITLE
[Bug] Listing pods

### ISSUE THREAD

**Issue by amy** [kris-nova/krex#9]
For some reason I can't list my pod resources when I click on a deployment. This may be an issue with permissions. Debugging needed.

**Comment by kris-nova** [comment]
So mapping pods to higher level abstractions is quite hard as it turns out.

Here is how we are doing it now: https://github.com/kris-nova/krex/blob/master/runtime/list.go#L95

Which works as long as the pod has a label that fits that criteria (assuming hardly any pods will actually work here)

We should find a better way...

**Comment by amy** [comment]
Fixed with this: https://github.com/kris-nova/krex/pull/23
